# yamllint disable rule:line-length
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: osl-backend-secret
  namespace: osl
spec:
  encryptedData:
    API_KEYS: AgCo9k+sdkk7HzVWZvhZ03dSJfsspett6kM6sJG08slRxXvdi5/tktOO1h/G8AwJuZMctYn0nVB68TgjrjlMxTm24Mh+x3JN6e6pRyXkL56mVFaYtCfBFfVGT+JOaCAVv3Du9smd0OmveclkVMAv+AUORMGsFX9f0tYEGw/V7wloPPsdd9KdxTLRhIFUdDsA5oiZTmH0jPqriO4h1byMo923pxQie4J4eD9I8Gc1T/P4eC51DeURJR0byD09UEuPopeDQgA1TCFJcTtyh9hY2X5Twf+ZzVB3VjDfJbRB6f8UGI1iL3jrT/CRApKYGIXMTRmde3WUOQ4GwKeabUqIuRHTlQ8FPSHkOcO/ajeBMxX4vPZQzkNd1rFFFvud/qqgvDqjhTIuyexFjpYITxWyMnKF1jHYvqfQGk109YkzAk305FI5kSSj91ewrESsLIP5UPlaGQrL5ic3u4E+L5W3OLgcBp+nFxt7k/5hwT1TuultzTOcFfxSwH7f7kPmAfOlJtoyXAm0778MsXlkmb+ify/Ebw5aPSsIPJBYoMu7xHpsacJFxB7fWmzc6EWTSWaMLtv97ohbHO+b+TBSabJkqeQEdQ6JsLCrG7pPplT3VJWEkJr6bkc7DkNGHgtVhGtqzgAbaG1aXeXjM+tK4wY5VCgd/bj/4ovpZ2qxR2M+fxnaccFl0ZZFeJiad8vraW75xBJjOG31zcuJBsNWS1ZNjngif0fCsRp+a25AD8mkq/4wqAEjrC4LsXBX+aOqMQ==
    DATABASE_URL: AgAxOsZyeUs5J6gDd6cpeycsXi9TQJI7oAaW8p0sGmLA72+i2lp2cC6k6/7HovvylIjJ8raisMF7huO2wuu0p3KivIrQPiDvO6tBNTJw4oy7OI51Fh33nkSFbDfzUqYZCEis6TwdTctLK+IjEjdaVtJ/lI6yq7WD1H9OJByUYAcSAvJGAkfzpVi1spSYcmM2CdzYTp6Ngo8L9LJvbD+S245dbZUnPQupn080ivfycFqwqkcQT9ldR3POkSRKctS4hqY7+EPgFKwfZULf8PCSx3MZOpvbIP0toPH8WFd6dpQGw8oLTdI85cxVLRr98ZzuZejO2UyGYH2mvry/xbpxATipnL7XI0oDIT6Wo3RX8g45tHfQnTeyPkjtf5XuaVh1rdY7w7QZ7PD1vtR96twSDldPFdL9MB41n4X7FUH43M806c9GUeCJFY56v2db5J1O7hdAUO/7Eq+AwoYfEuHUxev1RR8VjQkaUOLxv7t4PkYgTfXAQhUXrhD+5havWZY3Qp/J2X06grLz5M14ABXgbXEyvdkRuEoZUn2oF4plmxgOssl8xmUuJeU5H/TLzO8HM/oVNugxYet3Pkkqqcj/ImoZAof43Fpqp7O/WRp2OKoHa84UygCZKK142a5atIfgCC9rPPVpzFeCLI9Vd/Ots4uFGbFul4RiNx6CpQLQmmvft26ufqeoos0qeM/RCKoMzTe6TNCLzWVeOWA3KIAttV3XPMZpWZ158JBDLNpgb/hI87jMzajsHYG2+7+L0dgNsZ0F67ZyA6jRMnuqBe9Dl+JN/ZcWGF3mEqVARfiM5klb
  template:
    metadata:
      name: osl-backend-secret
      namespace: osl
