# yamllint disable rule:line-length
{{- if .Values.backend.sealedSecret.encryptedData }}
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ .Values.backend.existingSecret }}
  namespace: {{ .Release.Namespace }}
spec:
  encryptedData:
    {{- toYaml .Values.backend.sealedSecret.encryptedData | nindent 4 }}
  template:
    metadata:
      name: {{ .Values.backend.existingSecret }}
      namespace: {{ .Release.Namespace }}
{{- end }}
