apiVersion: v1
kind: Service
metadata:
  name: openstreetlifting-frontend
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "openstreetlifting.labels" . | nindent 4 }}
    {{- include "openstreetlifting.frontend.selectorLabels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- include "openstreetlifting.frontend.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.frontend.service.port }}
      targetPort: http
      protocol: TCP
