apiVersion: v1
kind: Secret
metadata:
  name: openstreetlifting-backend-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "openstreetlifting.labels" . | nindent 4 }}
type: Opaque
stringData:
  DB_PASSWORD: {{ .Values.backend.secret.dbPassword | quote }}
  DATABASE_URL: {{ .Values.backend.secret.databaseUrl | quote }}
  API_KEYS: {{ .Values.backend.secret.apiKeys | quote }}
