apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: openstreetlifting-ingress
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "openstreetlifting.labels" . | nindent 4 }}
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
spec:
  ingressClassName: traefik
  rules:
    - host: {{ .Values.ingress.frontendHost | quote }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: openstreetlifting-frontend
                port:
                  name: http
    - host: {{ .Values.ingress.backendHost | quote }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: openstreetlifting-backend
                port:
                  name: http
  {{- if .Values.ingress.tls }}
  tls:
    - hosts:
        - {{ .Values.ingress.frontendHost | quote }}
      secretName: openstreetlifting-frontend-tls
    - hosts:
        - {{ .Values.ingress.backendHost | quote }}
      secretName: openstreetlifting-backend-tls
  {{- end }}
